# Generated by Django 4.0 on 2022-03-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
